### ISSUE TITLE
jeepay-manager 服务异常

### ISSUE THREAD

**Issue by cjhqyz** [jeequan/jeepay#51]
## Bug概述
jeepay-manager服务报错

## 重现步骤
1. 使用docker compose 安装所有服务，具体指令如下
```shell
docker build -t jeepay-deps:latest -f docs/Dockerfile .
docker-compose up -d
```
2. 使用浏览器访问 http://dockerhost:9227/ (运营平台)或者http://dockerhost:9228/ (商户系统)

#### 1.浏览器控制台报错：

"系统异常[Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class io.netty.buffer.ByteBufAllocator]"
![image](https://github.com/jeequan/jeepay/assets/18466841/229489db-f706-4d8c-a931-959b7b62abc1)

#### 2.验证码不显示
![image](https://github.com/jeequan/jeepay/assets/18466841/19373e37-5516-4bea-8de9-567ef3eb9176)

## 期望行为
使用docker compost安装的程序，验证码可以正常显示，服务不再报错

## 附件
附上图片或日志，日志请用格式：
 
```
       __
      / /___  ___  ____  ____ ___  __
 __  / // _ \/ _ \/ __ \/ __ `/ / / /
/ /_/ //  __/  __/ /_/ / /_/ / /_/ /
\____/ \___/\___/ .___/\__,_/\__, /
               /_/          /____/
 :: Jeepay ::        (v2.2.0.RELEASE)
 适合互联网企业使用的开源支付系统 : https://www.jeequan.com
2023-07-09 14:35:03.829 INFO  [main] [c.j.j.m.b.JeepayMgrApplication] - Starting JeepayMgrApplication v2.2.0 using Java 1.8.0_312 on manager with PID 1 (/workspace/jeepay-app.jar started by root in /workspace)
2023-07-09 14:35:03.838 DEBUG [main] [c.j.j.m.b.JeepayMgrApplication] - Running with Spring Boot v2.4.8, Spring v5.3.8
2023-07-09 14:35:03.839 INFO  [main] [c.j.j.m.b.JeepayMgrApplication] - No active profile set, falling back to default profiles: default
2023-07-09 14:35:07.900 INFO  [main] [o.s.d.r.c.RepositoryConfigurationDelegate] - Multiple Spring Data modules found, entering strict repository configuration mode!
2023-07-09 14:35:07.912 INFO  [main] [o.s.d.r.c.RepositoryConfigurationDelegate] - Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2023-07-09 14:35:07.950 INFO  [main] [o.s.d.r.c.RepositoryConfigurationDelegate] - Finished Spring Data repository scanning in 15 ms. Found 0 Redis repository interfaces.
2023-07-09 14:35:09.686 INFO  [main] [o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@6aa8e115' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-07-09 14:35:09.698 INFO  [main] [o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker] - Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-07-09 14:35:10.796 INFO  [main] [o.s.b.w.e.t.TomcatWebServer] - Tomcat initialized with port(s): 9217 (http)
2023-07-09 14:35:10.818 INFO  [main] [o.a.c.h.Http11NioProtocol] - Initializing ProtocolHandler ["http-nio-9217"]
2023-07-09 14:35:10.823 INFO  [main] [o.a.c.c.StandardService] - Starting service [Tomcat]
2023-07-09 14:35:10.823 INFO  [main] [o.a.c.c.StandardEngine] - Starting Servlet engine: [Apache Tomcat/9.0.48]
2023-07-09 14:35:10.927 INFO  [main] [o.a.c.c.C.[.[.[/]] - Initializing Spring embedded WebApplicationContext
2023-07-09 14:35:10.928 INFO  [main] [o.s.b.w.s.c.ServletWebServerApplicationContext] - Root WebApplicationContext: initialization completed in 6913 ms
2023-07-09 14:35:11.477 INFO  [main] [c.a.d.s.b.a.DruidDataSourceAutoConfigure] - Init DruidDataSource
2023-07-09 14:35:12.223 INFO  [main] [c.a.d.p.DruidDataSource] - {dataSource-1} inited
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.4.2 
2023-07-09 14:35:13.223 WARN  [main] [c.b.m.c.m.TableInfoHelper] - Can not find table primary key in Class: "com.jeequan.jeepay.core.entity.SysUserRoleRela".
2023-07-09 14:35:14.259 INFO  [main] [o.m.p.j.JmsPoolConnectionFactory] - Provided ConnectionFactory implementation is JMS 2.0+ capable.
2023-07-09 14:35:15.858 WARN  [main] [c.b.m.c.m.TableInfoHelper] - Can not find table primary key in Class: "com.jeequan.jeepay.core.entity.SysRoleEntRela".
2023-07-09 14:35:17.974 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/', GET] with []
2023-07-09 14:35:17.975 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/*.html', GET] with []
2023-07-09 14:35:17.978 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/favicon.ico', GET] with []
2023-07-09 14:35:17.979 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.html', GET] with []
2023-07-09 14:35:17.979 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.css', GET] with []
2023-07-09 14:35:17.980 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.js', GET] with []
2023-07-09 14:35:17.980 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.png', GET] with []
2023-07-09 14:35:17.980 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.jpg', GET] with []
2023-07-09 14:35:17.980 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.jpeg', GET] with []
2023-07-09 14:35:17.981 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.svg', GET] with []
2023-07-09 14:35:17.981 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.ico', GET] with []
2023-07-09 14:35:17.981 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.webp', GET] with []
2023-07-09 14:35:17.981 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/*.txt', GET] with []
2023-07-09 14:35:17.982 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.xls', GET] with []
2023-07-09 14:35:17.983 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/**/*.mp4', GET] with []
2023-07-09 14:35:17.983 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/api/anon/**'] with []
2023-07-09 14:35:17.983 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/swagger-resources/**'] with []
2023-07-09 14:35:17.983 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure Ant [pattern='/v2/api-docs/**'] with []
2023-07-09 14:35:18.025 INFO  [main] [o.s.s.w.DefaultSecurityFilterChain] - Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@117632cf, org.springframework.security.web.context.SecurityContextPersistenceFilter@3be8821f, org.springframework.security.web.header.HeaderWriterFilter@df5f5c0, org.springframework.web.filter.CorsFilter@37ddb69a, org.springframework.security.web.authentication.logout.LogoutFilter@10567255, com.jeequan.jeepay.mgr.secruity.JeeAuthenticationTokenFilter@2fb68ec6, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@3b65e559, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@74a9c4b0, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@d71adc2, org.springframework.security.web.session.SessionManagementFilter@66b72664, org.springframework.security.web.access.ExceptionTranslationFilter@2e6ee0bc, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@51bde877]
2023-07-09 14:35:18.089 INFO  [main] [s.d.s.w.WebMvcPropertySourcedRequestMappingHandlerMapping] - Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2ControllerWebMvc#getDocumentation(String, HttpServletRequest)]
2023-07-09 14:35:18.503 INFO  [main] [o.s.b.a.w.s.WelcomePageHandlerMapping] - Adding welcome page: class path resource [static/index.html]
2023-07-09 14:35:19.291 WARN  [main] [o.s.b.a.f.FreeMarkerAutoConfiguration] - Cannot find template location(s): [classpath:/templates] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)
2023-07-09 14:35:19.549 INFO  [main] [o.a.c.h.Http11NioProtocol] - Starting ProtocolHandler ["http-nio-9217"]
2023-07-09 14:35:19.604 INFO  [main] [o.s.b.w.e.t.TomcatWebServer] - Tomcat started on port(s): 9217 (http) with context path ''
2023-07-09 14:35:19.607 INFO  [main] [s.d.s.w.p.DocumentationPluginsBootstrapper] - Documentation plugins bootstrapped
2023-07-09 14:35:19.619 INFO  [main] [s.d.s.w.p.DocumentationPluginsBootstrapper] - Found 1 custom documentation plugin(s)
2023-07-09 14:35:19.751 INFO  [main] [s.d.s.w.s.ApiListingReferenceScanner] - Scanning for api listing references
2023-07-09 14:35:20.071 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_1
2023-07-09 14:35:20.121 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_2
2023-07-09 14:35:20.123 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: addUsingPOST_1
2023-07-09 14:35:20.129 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: deleteUsingDELETE_1
2023-07-09 14:35:20.141 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_1
2023-07-09 14:35:20.149 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: updateUsingPUT_1
2023-07-09 14:35:20.183 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_3
2023-07-09 14:35:20.196 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: addUsingPOST_2
2023-07-09 14:35:20.199 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: deleteUsingDELETE_2
2023-07-09 14:35:20.222 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_2
2023-07-09 14:35:20.227 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: updateUsingPUT_2
2023-07-09 14:35:20.268 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_4
2023-07-09 14:35:20.278 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_3
2023-07-09 14:35:20.308 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: saveOrUpdateUsingPOST_1
2023-07-09 14:35:20.332 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_5
2023-07-09 14:35:20.360 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_6
2023-07-09 14:35:20.366 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: saveOrUpdateUsingPOST_2
2023-07-09 14:35:20.374 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: addUsingPOST_3
2023-07-09 14:35:20.376 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: deleteUsingDELETE_3
2023-07-09 14:35:20.378 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_4
2023-07-09 14:35:20.380 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: updateUsingPUT_3
2023-07-09 14:35:20.382 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_7
2023-07-09 14:35:20.412 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_8
2023-07-09 14:35:20.414 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_5
2023-07-09 14:35:20.423 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_9
2023-07-09 14:35:20.425 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: addUsingPOST_4
2023-07-09 14:35:20.428 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: deleteUsingDELETE_4
2023-07-09 14:35:20.431 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_6
2023-07-09 14:35:20.434 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: updateUsingPUT_4
2023-07-09 14:35:20.455 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_10
2023-07-09 14:35:20.459 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_7
2023-07-09 14:35:20.465 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: updateUsingPUT_5
2023-07-09 14:35:20.521 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_11
2023-07-09 14:35:20.524 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: deleteUsingDELETE_5
2023-07-09 14:35:20.526 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_8
2023-07-09 14:35:20.536 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_12
2023-07-09 14:35:20.538 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: addUsingPOST_5
2023-07-09 14:35:20.545 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_9
2023-07-09 14:35:20.549 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: updateUsingPUT_6
2023-07-09 14:35:20.556 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_13
2023-07-09 14:35:20.572 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_14
2023-07-09 14:35:20.574 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: addUsingPOST_6
2023-07-09 14:35:20.576 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: deleteUsingDELETE_6
2023-07-09 14:35:20.577 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_10
2023-07-09 14:35:20.584 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: updateUsingPUT_7
2023-07-09 14:35:20.592 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_15
2023-07-09 14:35:20.620 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: listUsingGET_16
2023-07-09 14:35:20.630 INFO  [main] [s.d.s.w.r.o.CachingOperationNameGenerator] - Generating unique operation named: detailUsingGET_11
2023-07-09 14:35:20.896 INFO  [ActiveMQ Task-1] [o.a.a.t.f.FailoverTransport] - Successfully connected to tcp://172.20.0.11:61616?wireFormat.maxInactivityDuration=0
2023-07-09 14:35:20.958 INFO  [main] [c.j.j.m.b.JeepayMgrApplication] - Started JeepayMgrApplication in 18.945 seconds (JVM running for 20.937)
2023-07-09 14:42:09.280 INFO  [http-nio-9217-exec-1] [o.a.c.c.C.[.[.[/]] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-07-09 14:42:09.280 INFO  [http-nio-9217-exec-1] [o.s.w.s.DispatcherServlet] - Initializing Servlet 'dispatcherServlet'
2023-07-09 14:42:09.287 INFO  [http-nio-9217-exec-1] [o.s.w.s.DispatcherServlet] - Completed initialization in 7 ms
2023-07-09 14:42:10.137 ERROR [http-nio-9217-exec-1] [c.j.j.c.e.BizExceptionResolver] - 公共捕捉[Exception]异常：
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1078)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:204)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError: null
	at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:86)
	at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24)
	at io.lettuce.core.AbstractRedisClient.connectionBuilder(AbstractRedisClient.java:222)
	at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:313)
	at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:278)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:211)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1459)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1247)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1230)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:979)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:359)
	at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144)
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:209)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:256)
	at com.jeequan.jeepay.core.cache.RedisUtil.setString(RedisUtil.java:74)
	at com.jeequan.jeepay.mgr.ctrl.anon.AuthController.vercode(AuthController.java:96)
	at com.jeequan.jeepay.mgr.ctrl.anon.AuthController$$FastClassBySpringCGLIB$$a10cd589.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.jeequan.jeepay.mgr.ctrl.anon.AuthController$$EnhancerBySpringCGLIB$$eafa095e.vercode(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063)
	... 49 common frames omitted
Caused by: java.lang.IllegalArgumentException: availableProcessors : 0 (expected: > 0)
	at io.netty.util.internal.ObjectUtil.checkPositive(ObjectUtil.java:80)
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:44)
	at io.netty.util.NettyRuntime$AvailableProcessorsHolder.availableProcessors(NettyRuntime.java:70)
	at io.netty.util.NettyRuntime.availableProcessors(NettyRuntime.java:98)
	at io.netty.buffer.PooledByteBufAllocator.<clinit>(PooledByteBufAllocator.java:101)
	... 93 common frames omitted
```

**Comment by cjhqyz** [comment]
jeepay-redis日志如下：
```
1:C 09 Jul 2023 15:22:00.710 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 09 Jul 2023 15:22:00.710 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 09 Jul 2023 15:22:00.710 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 09 Jul 2023 15:22:00.710 * monotonic clock: POSIX clock_gettime
1:M 09 Jul 2023 15:22:00.712 * Running mode=standalone, port=6379.
1:M 09 Jul 2023 15:22:00.712 # Server initialized
1:M 09 Jul 2023 15:22:00.712 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 09 Jul 2023 15:22:00.715 * Loading RDB produced by version 7.0.11
1:M 09 Jul 2023 15:22:00.715 * RDB age 788 seconds
1:M 09 Jul 2023 15:22:00.715 * RDB memory usage when created 0.82 Mb
1:M 09 Jul 2023 15:22:00.715 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 09 Jul 2023 15:22:00.715 * DB loaded from disk: 0.003 seconds
1:M 09 Jul 2023 15:22:00.715 * Ready to accept connections
1:signal-handler (1688916406) Received SIGTERM scheduling shutdown...
1:M 09 Jul 2023 15:26:47.015 # User requested shutdown...
1:M 09 Jul 2023 15:26:47.015 * Saving the final RDB snapshot before exiting.
1:M 09 Jul 2023 15:26:47.021 * DB saved on disk
1:M 09 Jul 2023 15:26:47.021 # Redis is now ready to exit, bye bye...
1:C 09 Jul 2023 15:27:06.727 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 09 Jul 2023 15:27:06.727 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 09 Jul 2023 15:27:06.727 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 09 Jul 2023 15:27:06.728 * monotonic clock: POSIX clock_gettime
1:M 09 Jul 2023 15:27:06.729 * Running mode=standalone, port=6379.
1:M 09 Jul 2023 15:27:06.729 # Server initialized
1:M 09 Jul 2023 15:27:06.729 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 09 Jul 2023 15:27:06.730 * Loading RDB produced by version 7.0.11
1:M 09 Jul 2023 15:27:06.730 * RDB age 19 seconds
1:M 09 Jul 2023 15:27:06.730 * RDB memory usage when created 0.82 Mb
1:M 09 Jul 2023 15:27:06.730 * Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 09 Jul 2023 15:27:06.730 * DB loaded from disk: 0.000 seconds
1:M 09 Jul 2023 15:27:06.730 * Ready to accept connections
```
